"""Merge tracer_kernel.py + inputs.py into one self-contained kernel file.

Kaggle script kernels package ONLY the code_file into /kaggle/src/script.py,
so a kernel cannot import sibling modules. inputs.py is a bare top-level
assignment `INPUTS = {...}`, so we prepend its whole body to the kernel source
and drop the import.

Usage:
    python finetune/kaggle/merge_kernel.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
KERNEL = HERE / "kernel"
SRC = (KERNEL / "tracer_kernel.py").read_text(encoding="utf-8")
INPUTS = (KERNEL / "inputs.py").read_text(encoding="utf-8")

assert "from inputs import INPUTS  # noqa: E402" in SRC

inputs_body = INPUTS.strip()
if not inputs_body.startswith("INPUTS ="):
    raise SystemExit("inputs.py does not start with INPUTS = assignment")

merged = SRC.replace(
    "from inputs import INPUTS  # noqa: E402",
    "# ---- embedded eval inputs (generated by gen_inputs.py) ----\n" + inputs_body,
)
merged = merged.replace(
    "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n",
    "",
    1,
)

out = KERNEL / "kg_tracer_single.py"
out.write_text(merged, encoding="utf-8")
print(f"wrote {out} ({len(merged)} chars)")
