#!/usr/bin/env python3
"""Inference on the FULL-trained LoRA adapter (kg-tracer-lffull output).

Loads the base Qwen3-0.6B + the full-trained adapter, mounted directly from
the training kernel's OUTPUT via kernel_sources (no download/upload round-trip),
merges, and runs single-shot inference on the embedded eval passages with the
derived STUDENT_PROMPT (thinking OFF). Writes predictions.jsonl + raw_<id>.txt
+ summary.csv.

Performance: bs=1 decode is GEMV-bound (~20 tok/s on T4, cublas gemv2T/gemvx),
so passages are sorted by length and decoded in batches (BATCH_SIZE env, default
4) — batching turns per-layer weight application into GEMMs: measured aggregate
22 / 85 / 164 tok/s at bs 1 / 4 / 8. Both T4s are used: one worker process per
GPU (torch.multiprocessing spawn), each loading its own fp16 model copy and
decoding half the passages (~2x wall). Schema-prefix injection forces JSON
output; a tolerant parser recovers entities/relationships from minor schema
drift (various relationship key spellings, unterminated arrays, stray chars).

Usage on Kaggle: python /kaggle/src/script.py  (metadata in kernel_inferfull/)
"""

import json
import os
import re
import sys

# Device selection is per-worker inside _infer_worker; the parent must NOT pin
# CUDA_VISIBLE_DEVICES (see main()).
os.environ.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")

# ---- embedded eval inputs (generated by gen_inputs.py, injected by merge) ----
# INPUTS_HERE

WORK = "/kaggle/working"
MODEL_PATH = "/kaggle/input/models/qwen-lm/qwen-3/transformers/0.6b/1"
ADAPTER_DIR = "/kaggle/input/notebooks/idalextan/kg-tracer-lffull/saves/qwen3-0.6b-graphrag-full-lf"


def log(msg: str) -> None:
    print(msg, flush=True)


def check_env() -> None:
    log("=== env ===")
    import torch

    log(f"torch: {torch.__version__} cuda={torch.cuda.is_available()}")
    if torch.cuda.is_available():
        log(f"gpu: {torch.cuda.get_device_name(0)}  count={torch.cuda.device_count()}")
    for p in (MODEL_PATH, ADAPTER_DIR):
        ok = os.path.exists(p)
        log(f"{'OK ' if ok else 'MISSING'} {p}")
        if not ok:
            raise SystemExit(f"required path missing: {p}")
    cfg = os.path.join(ADAPTER_DIR, "adapter_config.json")
    if not os.path.exists(cfg):
        raise SystemExit(f"no adapter_config.json under {ADAPTER_DIR}")


def _array_span(text: str, key: str, stop_key: str | None = None) -> str | None:
    """Return the JSON array value for `key` (with surrounding brackets).

    Respects string/nesting depth. If the array never closes, stop at the
    next `stop_key` (so an unterminated entities array does not swallow the
    relationships that follow) and return the unclosed prefix — the caller
    repairs it by appending ']'. Returns None if the key or its array is
    absent.
    """
    i = text.find('"' + key + '"')
    if i < 0:
        return None
    j = text.find("[", i)
    if j < 0:
        return None
    limit = len(text)
    if stop_key:
        k = text.find('"' + stop_key + '"', i + len(key))
        if k > j:
            limit = k
    depth = 0
    in_str = False
    esc = False
    for idx in range(j, min(limit + 1, len(text))):
        c = text[idx]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
        elif c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                return text[j : idx + 1]
    return text[j:limit]


def _fix_array(seg: str | None, item_key: str) -> list[dict]:
    """Best-effort parse of a possibly-broken array into a list of dicts.

    Tries, in order: strict parse, append ']', prepend '[', per-object salvage
    (each non-nested {...} parsed independently with light char repairs).
    Only dicts carrying `item_key` (e.g. "title" or "source") are kept.
    """
    if not seg:
        return []
    cands = [seg]
    if not seg.endswith("]"):
        cands.append(seg + "]")
    if not seg.startswith("["):
        cands.append("[" + seg)
    cands += [seg.replace(")", "}"), seg.replace("),", "},")]
    for c in cands:
        try:
            v = json.loads(c)
        except Exception:  # noqa: BLE001
            continue
        if isinstance(v, list):
            return [d for d in v if isinstance(d, dict) and d.get(item_key)]
    # per-object salvage
    out = []
    for o in re.findall(r"\{[^{}]*\}", seg):
        try:
            d = json.loads(o.replace(")", "}"))
        except Exception:  # noqa: BLE001
            continue
        if isinstance(d, dict) and d.get(item_key):
            out.append(d)
    return out


def _parse_answer(raw: str) -> tuple[dict, str]:
    """Parse a completion into {entities, relationships} with repair.

    Returns (parsed, status) where status is "ok" (strict JSON parse) or
    "repaired:N" (recovered N of {entities,relationships} arrays by salvage).
    Never raises; on total failure returns empty lists with status "failed".
    """
    raw = raw.strip()
    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end > start:
        try:
            obj = json.loads(raw[start : end + 1])
            return {"entities": obj.get("entities", []),
                    "relationships": obj.get("relationships", [])}, "ok"
        except Exception:  # noqa: BLE001
            pass
    entities = _fix_array(_array_span(raw, "entities", stop_key="rel"), "title")
    # the model is unstable about the relationship key name: it has emitted
    # "relationships", the misspelt "relationship", and "relations". Try the
    # candidates in order (the standard one first), bounded by the entities
    # array on the left.
    relationships = []
    for key in ("relationships", "relations", "relationship"):
        span = _array_span(raw, key)
        if span:
            relationships = _fix_array(span, "source")
            if relationships:
                break
    if not relationships:
        # degenerate emission seen in the wild:
        # {"relationship": ["ENGLAND", "RUDDER"], "strength": 9} — a two-element
        # array standing in for source/target. Convert to the canonical form.
        rels = []
        for m in re.finditer(
            r'\{\s*"relationship"\s*:\s*\[("[^"]*")\s*,\s*("[^"]*")\]\s*(?:,\s*"strength"\s*:\s*([0-9.]+))?\s*\}',
            raw,
        ):
            src, tgt, strength = m.groups()
            d = {"source": json.loads(src), "target": json.loads(tgt)}
            if strength:
                d["strength"] = float(strength)
            rels.append(d)
        relationships = rels
    if entities or relationships:
        return {"entities": entities, "relationships": relationships}, "repaired"
    return {"entities": [], "relationships": []}, "failed"


def install() -> None:
    """Neutralise torchao only; no transformers/peft downgrade.

    torchao 0.10.0 preinstalled in the Kaggle image makes peft's
    `PeftModel.from_pretrained` hard-fail before reading the adapter.
    Uninstalling it is enough (inference does not use torchao).

    Earlier versions downgraded to the v4-validated matrix (transformers
    4.57.x / peft 0.18.1) but the Kaggle pip backend repeatedly hung mid-
    install on those runs. Inference does not need the training matrix, so we
    now try the preinstalled transformers 5.0 / peft 0.19.1 directly and only
    uninstall torchao (with a hard timeout so a hung backend fails fast).
    """
    import importlib.metadata as md
    import subprocess

    log("=== install stack ===")

    def ver(pkg: str) -> str:
        try:
            return md.version(pkg)
        except md.PackageNotFoundError:
            return "MISSING"

    for p in ("torchao", "transformers", "peft"):
        log(f"pre {p}: {ver(p)}")
    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "uninstall", "-y", "torchao"],
            timeout=60, check=True, stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        log("uninstalled torchao")
    except Exception as e:  # noqa: BLE001
        log(f"torchao uninstall failed (continuing): {e}")
    # No transformers/peft downgrade: the Kaggle pip backend has repeatedly
    # hung mid-install, and inference does not actually need the training
    # matrix — try the preinstalled transformers 5.0 / peft 0.19.1 directly.
    for p in ("torchao", "transformers", "peft"):
        log(f"post {p}: {ver(p)}")


def _infer_worker(rank: int, nprocs: int, passages: list[dict]) -> list[dict]:
    """Run batch inference for `passages` on GPU `rank`. Top-level for spawn.

    Each worker process pins its own CUDA_VISIBLE_DEVICES so two Kaggle T4s are
    used (each loads its own fp16 copy of model+adapter and decodes a half of
    the passages). Writes raw_<id>.txt into WORK as it goes; returns the parsed
    rows so the parent can merge them into predictions.jsonl.
    """
    os.environ["CUDA_VISIBLE_DEVICES"] = str(rank)
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    log(f"[gpu{rank}] worker on {torch.cuda.get_device_name(0)}; "
        f"{len(passages)} passages")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
    # FP16 load (bf16 also works — decode is GEMV-bound so dtype does not matter
    # at bs=1 — but fp16 is the training-validated path).
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH, torch_dtype=torch.float16, device_map="cuda",
        trust_remote_code=True,
    )
    model = PeftModel.from_pretrained(
        model, ADAPTER_DIR, torch_dtype=torch.float16
    ).merge_and_unload()
    model.eval()

    prompt = INPUTS["student_prompt"]
    rows: list[dict] = []
    # Batch decode: bs=1 decode is GEMV-bound (~20 tok/s on T4; cublas gemv2T/
    # gemvx kernels, memory-bandwidth limited, fp16 vs bf16 makes no diff).
    # Batching N sequences turns weight application into a GEMM: measured
    # 22 -> 85 -> 164 aggregate tok/s at bs 1/4/8. Passages differ in length,
    # so sort by length and pack consecutive ones to keep padding waste small.
    sorted_ps = sorted(enumerate(passages), key=lambda ep: len(ep[1]["text"]))
    schema_prefix = '{"entities": ['
    prefix_ids = tokenizer.encode(schema_prefix, add_special_tokens=False)
    batch_size = int(os.environ.get("BATCH_SIZE", "4"))

    def run_batch(batch: list[tuple[int, dict]]) -> None:
        texts = []
        for _, p in batch:
            content = f"{prompt}\n{p['text']}"
            texts.append(tokenizer.apply_chat_template(
                [{"role": "user", "content": content}], tokenize=False,
                add_generation_prompt=True, enable_thinking=False))
        enc = tokenizer(texts, return_tensors="pt", padding=True)
        prefix_t = torch.tensor([prefix_ids] * len(batch), dtype=torch.long,
                                device="cuda")
        gen_input = torch.cat([enc["input_ids"].to("cuda"), prefix_t], dim=1)
        attn = torch.cat([enc["attention_mask"].to("cuda"),
                          torch.ones(len(batch), prefix_t.shape[1],
                                     dtype=torch.long, device="cuda")], dim=1)
        # True (unpadded) prompt length per row — the generated tail starts at
        # mask.sum(). Slice from prompt_end = mask.sum() - prefix_len so the
        # schema prefix stays in the decoded raw (parser expects it).
        prompt_ends = (attn.sum(dim=1) - len(prefix_ids)).tolist()
        with torch.no_grad():
            gen = model.generate(
                input_ids=gen_input, attention_mask=attn,
                max_new_tokens=8192, do_sample=True,
                temperature=0.7, top_p=0.95, repetition_penalty=1.15,
            )
        for bi, (_orig_i, p) in enumerate(batch):
            out_ids = gen[bi][int(prompt_ends[bi]):]
            raw = tokenizer.decode(out_ids, skip_special_tokens=True)
            with open(os.path.join(WORK, f"raw_{p['id']}.txt"), "w",
                      encoding="utf-8") as f:
                f.write(raw)
            try:
                parsed, status = _parse_answer(raw)
            except Exception as e:  # noqa: BLE001
                status = f"except:{e}"
                parsed = {"entities": [], "relationships": []}
            if status != "ok":
                log(f"[gpu{rank}][{p['id']}]: PARSE {status} len={len(raw)}")
            rows.append({"id": p["id"],
                         "entities": parsed.get("entities", []),
                         "relationships": parsed.get("relationships", [])})
            log(f"[gpu{rank}][{p['id']}]: entities={len(rows[-1]['entities'])} "
                f"rels={len(rows[-1]['relationships'])} raw_len={len(raw)}")

    for start in range(0, len(sorted_ps), batch_size):
        run_batch(sorted_ps[start:start + batch_size])
    log(f"[gpu{rank}] worker done, {len(rows)} rows")
    return rows


def _load_passages() -> list[dict]:
    """Load eval passages from a file if available, else the embedded INPUTS.

    File sources, in priority order:
      1. PASSAGES_FILE env (explicit override),
      2. the mounted trace-test-passages dataset (full-scale 699 test).
    Each line must be {"id": ..., "text": ...}.
    """
    cands = [os.environ.get("PASSAGES_FILE"),
             "/kaggle/input/trace-test-passages/test_passages.jsonl",
             "/kaggle/input/datasets/idalextan/trace-test-passages/test_passages.jsonl"]
    for pf in cands:
        if pf and os.path.exists(pf):
            log(f"reading passages from {pf}")
            out = []
            with open(pf, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        r = json.loads(line)
                        out.append({"id": r["id"], "text": r["text"]})
            return out
    log("WARNING: no passages file found; falling back to embedded INPUTS "
        "(%d tracer passages). /kaggle/input top-level: %s" % (
            len(INPUTS["passages"]),
            ", ".join(os.listdir("/kaggle/input")) if os.path.isdir("/kaggle/input") else "n/a"))
    return list(INPUTS["passages"])


def infer(limit: int | None = None) -> None:
    passages = _load_passages()
    if limit:
        passages = passages[:limit]
    log(f"=== inference on {len(passages)} eval passages (max_new_tokens=8192) ===")
    import torch

    n_gpu = torch.cuda.device_count()
    log(f"CUDA devices available: {n_gpu}")
    # Spawn one worker per GPU (each loads its own model copy + decode half the
    # passages -> ~2x wall throughput on two T4s). Single-GPU falls back to one
    # worker (rank 0).
    nprocs = n_gpu if n_gpu >= 2 else 1
    if nprocs == 1:
        rows = _infer_worker(0, 1, passages)
    else:
        from torch import multiprocessing as mp
        chunks = [passages[i::nprocs] for i in range(nprocs)]
        ctx = mp.get_context("spawn")
        procs = []
        results: dict[int, list[dict]] = {}
        q = ctx.Queue()
        for rank in range(nprocs):
            p = ctx.Process(target=_worker_send, args=(rank, chunks[rank], q, nprocs))
            p.start()
            procs.append(p)
        for _ in range(nprocs):
            rank, part = q.get()
            results[rank] = part
        for p in procs:
            p.join(timeout=3600)
        rows = []
        for rank in range(nprocs):
            rows.extend(results.get(rank, []))

    pred_path = os.path.join(WORK, "predictions.jsonl")
    with open(pred_path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    log(f"wrote {pred_path} ({len(rows)} rows)")
    with open(os.path.join(WORK, "summary.csv"), "w", encoding="utf-8") as f:
        f.write("id,entities,relationships\n")
        for r in rows:
            f.write(f"{r['id']},{len(r['entities'])},{len(r['relationships'])}\n")


def _worker_send(rank: int, passages: list[dict], q, nprocs: int) -> None:
    """spawn target: run worker and ship its rows back on the queue."""
    try:
        q.put((rank, _infer_worker(rank, nprocs, passages)))
    except Exception as e:  # noqa: BLE001
        log(f"[gpu{rank}] worker failed: {e}")
        q.put((rank, []))


def main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=None,
                        help="infer only the first N passages (smoke check); "
                             "defaults to env TRACE_LIMIT if set")
    args = parser.parse_args(argv)
    check_env()
    install()
    n = args.limit
    if n is None and os.environ.get("TRACE_LIMIT"):
        n = int(os.environ["TRACE_LIMIT"])
    log(f"=== inference {'(limit=%d)' % n if n else '(all passages)'} ===")
    infer(limit=n)
    log("=== DONE ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
