#!/usr/bin/env python3
"""Inference on the llamafactory dual-GPU tracer adapter.

Loads base Qwen3-0.6B + the H4-new-data adapter (kg-tracer-lf-adapter, dataset
idalextan/kg-tracer-lf-adapter), merges, and single-shot infers on the 10
embedded tracer-eval passages with the derived STUDENT_PROMPT (thinking OFF,
sampling temp 0.7 / top_p 0.95 / rep 1.15). Writes predictions.jsonl +
raw_<id>.txt. Train and serve use the SAME H4 prompt (ADR-0001 invariant).

Usage on Kaggle: python /kaggle/src/script.py  (metadata in kernel_infer/)
"""

import json
import os
import sys

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")
os.environ.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")

# ---- embedded eval inputs (generated by gen_inputs.py, injected by merge) ----
# INPUTS_HERE

WORK = "/kaggle/working"
MODEL_PATH = "/kaggle/input/models/qwen-lm/qwen-3/transformers/0.6b/1"
ADAPTER_DIR = "/kaggle/input/datasets/idalextan/kg-tracer-lf-adapter"


def log(msg: str) -> None:
    print(msg, flush=True)


def check_env() -> None:
    log("=== env ===")
    import torch

    log(f"torch: {torch.__version__} cuda={torch.cuda.is_available()}")
    if torch.cuda.is_available():
        log(f"gpu: {torch.cuda.get_device_name(0)}  count={torch.cuda.device_count()}")
    for p in (MODEL_PATH, ADAPTER_DIR):
        ok = os.path.exists(p)
        log(f"{'OK ' if ok else 'MISSING'} {p}")
        if not ok:
            raise SystemExit(f"required path missing: {p}")
    cfg = os.path.join(ADAPTER_DIR, "adapter_config.json")
    if not os.path.exists(cfg):
        raise SystemExit(f"no adapter_config.json under {ADAPTER_DIR}")


def _parse_answer(raw: str) -> dict:
    raw = raw.strip()
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"no JSON object in completion: {raw[:200]!r}")
    return json.loads(raw[start : end + 1])


def install() -> None:
    """Pin the stack the v4 training kernel validated, and neutralise torchao.

    The Kaggle image pre-installs torchao 0.10.0; peft 0.18.1's
    `PeftModel.from_pretrained` hard-fails on it ("only versions above 0.16.0
    are supported") before it even reads the adapter. Uninstalling is enough —
    inference does not use torchao.
    """
    import importlib.metadata as md
    import subprocess

    log("=== install stack ===")

    def ver(pkg: str) -> str:
        try:
            return md.version(pkg)
        except md.PackageNotFoundError:
            return "MISSING"

    for p in ("torchao", "transformers", "peft"):
        log(f"pre {p}: {ver(p)}")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "uninstall", "-y", "torchao"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    subprocess.check_call(
        [
            sys.executable, "-m", "pip", "install", "--quiet",
            "transformers>=4.49.0,<5.0.0",
            "peft>=0.14.0,<=0.18.1",
        ]
    )
    for p in ("torchao", "transformers", "peft"):
        log(f"post {p}: {ver(p)}")


def infer() -> None:
    log("=== inference on 10 eval passages (max_new_tokens=8192) ===")
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH, torch_dtype=torch.bfloat16, device_map="cuda", trust_remote_code=True
    )
    model = PeftModel.from_pretrained(model, ADAPTER_DIR).merge_and_unload()
    model.eval()

    prompt = INPUTS["student_prompt"]
    rows = []
    for i, p in enumerate(INPUTS["passages"], 1):
        content = f"{prompt}\n{p['text']}"
        msgs = [{"role": "user", "content": content}]
        text = tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )
        inputs = tokenizer([text], return_tensors="pt").to("cuda")
        with torch.no_grad():
            # Greedy (do_sample=False) degenerates to repetition loops on long
            # structured output (HF docs: greedy "breaks down ... begins to
            # repeat"; Qwen3's own default is sampling temp 0.6/top_p 0.95).
            # temperature 0.7 + top_p 0.95 + repetition_penalty 1.15 follows
            # the documented ranges for structured output.
            gen = model.generate(
                **inputs, max_new_tokens=8192, do_sample=True,
                temperature=0.7, top_p=0.95, repetition_penalty=1.15,
            )
        out_ids = gen[0][inputs["input_ids"].shape[1]:]
        raw = tokenizer.decode(out_ids, skip_special_tokens=True)
        with open(os.path.join(WORK, f"raw_{p['id']}.txt"), "w", encoding="utf-8") as f:
            f.write(raw)
        try:
            parsed = _parse_answer(raw)
        except Exception as e:  # noqa: BLE001
            log(f"[{i}/10] {p['id']}: PARSE FAIL ({e}) len={len(raw)}")
            parsed = {"entities": [], "relationships": []}
        rows.append({"id": p["id"], "entities": parsed.get("entities", []),
                     "relationships": parsed.get("relationships", [])})
        log(f"[{i}/10] {p['id']}: entities={len(rows[-1]['entities'])} "
            f"rels={len(rows[-1]['relationships'])} raw_len={len(raw)}")

    pred_path = os.path.join(WORK, "predictions.jsonl")
    with open(pred_path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    log(f"wrote {pred_path} ({len(rows)} rows)")
    # CSV summary so Kaggle output listing is greppable without opening files
    with open(os.path.join(WORK, "summary.csv"), "w", encoding="utf-8") as f:
        f.write("id,entities,relationships\n")
        for r in rows:
            f.write(f"{r['id']},{len(r['entities'])},{len(r['relationships'])}\n")


def main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args(argv)
    check_env()
    install()
    infer()
    log("=== DONE ===")
    return 0


sys.exit(main())
