#!/usr/bin/env python3
"""Inference on the llamafactory dual-GPU tracer adapter.

Loads base Qwen3-0.6B + the H4-new-data adapter (kg-tracer-lf-adapter, dataset
idalextan/kg-tracer-lf-adapter), merges, and single-shot infers on the 10
embedded tracer-eval passages with the derived STUDENT_PROMPT (thinking OFF,
sampling temp 0.7 / top_p 0.95 / rep 1.15). Writes predictions.jsonl +
raw_<id>.txt. Train and serve use the SAME H4 prompt (ADR-0001 invariant).

Usage on Kaggle: python /kaggle/src/script.py  (metadata in kernel_infer/)
"""

import json
import os
import sys

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")
os.environ.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")

# ---- embedded eval inputs (generated by gen_inputs.py, injected by merge) ----
INPUTS = {
 "student_prompt": "-GOAL-\nGiven a text document that is potentially relevant to this activity and a list of entity types, identify all entities of those types from the text and all relationships among the identified entities.\n\n-STEPS-\n1. Identify all entities. For each identified entity, record the following:\n- title: name of the entity in canonical uppercase form, consistent across the whole output\n- type: one of PERSON, ORGANIZATION, GEO, EVENT, CONCEPT\n- description: a concise factual description of the entity's attributes and role in the text (one or two sentences directly supported by the text; include numeric details such as dates, counts and measurements when the text states them)\n\n2. From the entities recorded in step 1, identify all pairs of (source, target) that are *clearly related* to each other.\nFor each related pair, record the following:\n- source: title of the source entity, as recorded in step 1\n- target: title of the target entity, as recorded in step 1\n- description: why you think the source entity and the target entity are related, grounded in the text\n- strength: a numeric score from 0 to 10 indicating how strong the relation between the source and target entities is\n\n-OUTPUT-\nReturn a single JSON object with exactly two keys:\n{\"entities\": [{\"title\", \"type\", \"description\"}], \"relationships\": [{\"source\", \"target\", \"description\", \"strength\"}]}\n\"source\" and \"target\" must exactly equal the \"title\" of an entity listed in \"entities\". Only include entities and relationships explicitly supported by the text; never invent facts, entities or relations. If nothing can be extracted, return {\"entities\": [], \"relationships\": []}.",
 "passages": [
  {
   "id": "wikipedia-02909",
   "text": "Arne Kaijser (born 1950) is a professor emeritus of history of technology at the KTH Royal Institute of Technology in Stockholm, and a former president of the Society for the History of Technology. Kaijser has published two books in Swedish: Stadens ljus. Etableringen av de första svenska gasverken and I fädrens spår. Den svenska infrastrukturens historiska utveckling och framtida utmaningar, and has co-edited several anthologies. Kaijser is a member of the Royal Swedish Academy of Engineering Sciences since 2007 and also a member of the editorial board of two scientific journals: Journal of Urban Technology and Centaurus. Lately, he has been occupied with the history of Large Technical Systems."
  },
  {
   "id": "arxiv-00944",
   "text": "the three - gluon vertex is a basic object of interest in nonabelian gauge theory . it contains important structural information , in particular on infrared divergences , and also figures prominently in the schwinger - dyson equations . at the one - loop level , it has been calculated and analyzed by a number of authors . here we use the worldline formalism to unify the calculations of the scalar , spinor and gluon loop contributions to the one - loop vertex , leading to an extremely compact representation . the susy - related sum rule found by binger and brodsky follows from an off - shell extension of the bern - kosower replacement rules . we explain the relation of the structure of our representation to the low - energy effective action ."
  },
  {
   "id": "wikipedia-01557",
   "text": "Its territory can be subdivided into four terrestrial ecoregions of the Palearctic realm namely within the Illyrian deciduous forests, Balkan mixed forests, Pindus Mountains mixed forests and Dinaric Mountains mixed forests. Approximately 3,500 different species of plants can be found in Albania which refers principally to a Mediterranean and Eurasian character. The country maintains a vibrant tradition of herbal and medicinal practices. At the minimum 300 plants growing locally are used in the preparation of herbs and medicines. The trees within the forests are primarily fir, oak, beech and pine. Conservation Albania has been an active participant in numerous international agreements and conventions aimed at strengthing its commitment to the preservation and sustainable management of biological diversity. Since 1994, the country is a party to the Convention on Biological Diversity (CBD) and its associated Cartagena and Nagoya Protocols. To uphold these commitments, it has developed and implemented a comprehensive National Biodiversity Strategy and Action Plan (NBSAP). Furthermore, Albania has established a partnership with the International Union for Conservation of Nature (IUCN), advancing its conservation efforts on both national and international scales. Guided by the IUCN, the country has made substantial progress in the foundation of protected areas within its boundaries, encompassing 12 national parks among others Butrint, Karaburun-Sazan, Llogara, Prespa and Vjosa. As a signatory to the Ramsar Convention, Albania has granted special recognition upon four wetlands, designating them as Wetlands of International Importance, including Buna-Shkodër, Butrint, Karavasta and Prespa. The country's dedication to protection extends further into the sphere of UNESCO's World Network of Biosphere Reserves, operating within the framework of the Man and the Biosphere Programme, evidenced by its engagement in the Ohrid-Prespa Transboundary Biosphere Reserve."
  },
  {
   "id": "wikipedia-02266",
   "text": "Audi AG () is a German automotive manufacturer of luxury vehicles headquartered in Ingolstadt, Bavaria, Germany. A subsidiary of the Volkswagen Group, Audi produces vehicles in nine production facilities worldwide. The origins of the company are complex, dating back to the early 20th century and the initial enterprises (Horch and the Audiwerke) founded by engineer August Horch (1868–1951). Two other manufacturers (DKW and Wanderer) also contributed to the foundation of Auto Union in 1932. The modern Audi era began in the 1960s, when Auto Union was acquired by Volkswagen from Daimler-Benz. After relaunching the Audi brand with the 1965 introduction of the Audi F103 series, Volkswagen merged Auto Union with NSU Motorenwerke in 1969, thus creating the present-day form of the company. The company name is based on the Latin translation of the surname of the founder, August Horch. , meaning \"listen\", becomes in Latin. The four rings of the Audi logo each represent one of four car companies that banded together to create Audi's predecessor company, Auto Union. Audi's slogan is , which is translated as \"Progress through Technology\". Audi, along with German brands BMW and Mercedes-Benz, is among the best-selling luxury automobile brands in the world. History Birth of the company and its name Automobile company Wanderer was originally established in 1885, later becoming a branch of Audi AG. Another company, NSU, which also later merged into Audi, was founded during this time, and later supplied the chassis for Gottlieb Daimler's four-wheeler. On 14 November 1899, August Horch (1868–1951) established the company A. Horch & Cie. in the Ehrenfeld district of Cologne. In 1902, he moved with his company to Reichenbach im Vogtland. On 10 May 1904, he founded the August Horch & Cie. Motorwagenwerke AG, a joint-stock company in Zwickau (State of Saxony)."
  },
  {
   "id": "wikipedia-01974",
   "text": "NGC 772 has a diameter of 240,000 light-years and the system is 114 million light-years from Earth. Another spiral galaxy in Aries is NGC 673, a face-on class SAB(s)c galaxy. It is a weakly barred spiral galaxy with loosely wound arms. It has no ring and a faint bulge and is 2.5 by 1.9 arcminutes. It has two primary arms with fragments located farther from the core. 171,000 light-years in diameter, NGC 673 is 235 million light-years from Earth. NGC 678 and NGC 680 are a pair of galaxies in Aries that are only about 200,000 light-years apart. Part of the NGC 691 group of galaxies, both are at a distance of approximately 130 million light-years. NGC 678 is an edge-on spiral galaxy that is 4.5 by 0.8 arcminutes. NGC 680, an elliptical galaxy with an asymmetrical boundary, is the brighter of the two at magnitude 12.9; NGC 678 has a magnitude of 13.35. Both galaxies have bright cores, but NGC 678 is the larger galaxy at a diameter of 171,000 light-years; NGC 680 has a diameter of 72,000 light-years. NGC 678 is further distinguished by its prominent dust lane. NGC 691 itself is a spiral galaxy slightly inclined to our line of sight. It has multiple spiral arms and a bright core. Because it is so diffuse, it has a low surface brightness. It has a diameter of 126,000 light-years and is 124 million light-years away. NGC 877 is the brightest member of an 8-galaxy group that also includes NGC 870, NGC 871, and NGC 876, with a magnitude of 12.53. It is 2.4 by 1.8 arcminutes and is 178 million light-years away with a diameter of 124,000 light-years. Its companion is NGC 876, which is about 103,000 light-years from the core of NGC 877."
  },
  {
   "id": "wikipedia-01420",
   "text": "In 2016, Alberta continued to have the youngest population among the provinces with a median age of 36.7 years, compared with the national median of 41.2 years. Also in 2016, Alberta had the smallest proportion of seniors (12.3%) among the provinces and one of the highest population shares of children (19.2%), further contributing to Alberta's young and growing population. About 81% of the population lives in urban areas and only about 19% in rural areas. The Calgary–Edmonton Corridor is the most urbanized area in the province and is one of the most densely populated areas of Canada. Many of Alberta's cities and towns have experienced very high rates of growth in recent history. Alberta's population rose from 73,022 in 1901 to 3,290,350 according to the 2006 census. According to the 2016 census Alberta has 779,155 residents (19.2%) between the ages of 0–14, 2,787,805 residents (68.5%) between the ages of 15–64, and 500,215 residents (12.3%) aged 65 and over. Additionally, as per the 2016 census, 1,769,500 residents hold a postsecondary certificate, diploma or degree, 895,885 residents have obtained a secondary (high) school diploma or equivalency certificate, and 540,665 residents do not have any certificate, diploma or degree. Municipalities Language As of the 2021 Canadian Census, the ten most spoken languages in the province included English (4,109,720 or 98.37%), French (260,415 or 6.23%), Tagalog (172,625 or 4.13%), Punjabi (126,385 or 3.03%), Spanish (116,070 or 2.78%), Hindi (94,015 or 2.25%), Mandarin (82,095 or 1.97%), Arabic (76,760 or 1.84%), Cantonese (74,960 or 1.79%), and German (65,370 or 1.56%). The question on knowledge of languages allows for multiple responses. As of the 2016 census, English is the most common mother tongue, with 2,991,485 native speakers."
  },
  {
   "id": "wikipedia-01252",
   "text": "Biggest seas in Atlantic Ocean Top large seas: Sargasso Sea3.5 million km2 Caribbean Sea2.754 million km2 Mediterranean Sea2.510 million km2 Gulf of Guinea2.35 million km2 Gulf of Mexico1.550 million km2 Norwegian Sea1.383 million km2 Hudson Bay1.23 million km2 Greenland Sea1.205 million km2 Argentine Sea1 million km2 Labrador Sea841,000 km2 Irminger Sea780,000 km2 Baffin Bay689,000 km2 North Sea575,000 km2 Black Sea436,000 km2 Baltic Sea377,000 km2 Libyan Sea350,000 km2 Levantine Sea320,000 km2 Celtic Sea300,000 km2 Tyrrhenian Sea275,000 km2 Gulf of Saint Lawrence226,000 km2 Bay of Biscay223,000 km2 Aegean Sea214,000 km2 Ionian Sea169,000 km2 Balearic Sea150,000 km2 Adriatic Sea138,000 km2 Gulf of Bothnia116,300 km2 Sea of Crete95,000 km2 Gulf of Maine93,000 km2 Ligurian Sea80,000 km2 English Channel75,000 km2 James Bay68,300 km2 Bothnian Sea66,000 km2 Gulf of Sidra57,000 km2 Sea of the Hebrides47,000 km2 Irish Sea46,000 km2 Sea of Azov39,000 km2 Bothnian Bay36,800 km2 Gulf of Venezuela17,840 km2 Bay of Campeche16,000 km2 Gulf of Lion15,000 km2 Sea of Marmara11,350 km2 Wadden Sea10,000 km2 Archipelago Sea8,300 km2 Bathymetry The bathymetry of the Atlantic is dominated by a submarine mountain range called the Mid-Atlantic Ridge (MAR). It runs from 87°N or south of the North Pole to the subantarctic Bouvet Island at 54°S. Expeditions to explore the bathymertry of the Atlantic include the Challenger expedition and the German Meteor expedition; , Columbia University's Lamont–Doherty Earth Observatory and the United States Navy Hydrographic Office conduct research on the ocean. Mid-Atlantic Ridge The MAR divides the Atlantic longitudinally into two halves, in each of which a series of basins are delimited by secondary, transverse ridges. The MAR reaches above along most of its length, but is interrupted by larger transform faults at two places: the Romanche Trench near the Equator and the Gibbs Fracture Zone at 53°N."
  },
  {
   "id": "wikipedia-00083",
   "text": "In 2009, Bryant–Denny Stadium and Jordan-Hare Stadium became the homes of the Alabama High School Athletic Association state football championship games, after previously being held at Legion Field in Birmingham. Transportation Aviation Major airports with sustained operations in Alabama include Birmingham-Shuttlesworth International Airport (BHM), Huntsville International Airport (HSV), Dothan Regional Airport (DHN), Mobile Regional Airport (MOB), Montgomery Regional Airport (MGM), Northwest Alabama Regional Airport (MSL) and Northeast Alabama Regional Airport (GAD). Rail For rail transport, Amtrak schedules the Crescent, a daily passenger train, running from New York to New Orleans with station stops at Anniston, Birmingham, and Tuscaloosa. Roads Alabama has six major interstate routes: Interstate 65 (I-65) travels north–south roughly through the middle of the state; I-20/I-59 travel from the central west Mississippi state line to Birmingham, where I-59 continues to the north-east corner of the state and I-20 continues east towards Atlanta; I-85 originates in Montgomery and travels east-northeast to the Georgia state line, providing a main thoroughfare to Atlanta; and I-10 traverses the southernmost portion of the state, traveling from west to east through Mobile. I-22 enters the state from Mississippi and connects Birmingham with Memphis, Tennessee. In addition, there are currently five auxiliary interstate routes in the state: I-165 in Mobile, I-359 in Tuscaloosa, I-459 around Birmingham, I-565 in Decatur and Huntsville, and I-759 in Gadsden. A sixth route, I-685, will be formed when I-85 is rerouted along a new southern bypass of Montgomery. A proposed northern bypass of Birmingham will be designated as I-422. Since a direct connection from I-22 to I-422 will not be possible, I-222 has been proposed, as well. Several U.S. Highways also pass through the state, such as U.S. Route 11 (US-11), US-29, US-31, US-43, US-45, US-72, US-78, US-80, US-82, US-84, US-90, US-98, US-231, US-278, US-280, US-331, US-411, and US-431."
  },
  {
   "id": "wikipedia-01421",
   "text": "This is followed by Tagalog, with 99,035 speakers, German, with 80,050 speakers, French, with 72,150 native speakers, and Punjabi, with 68,695 speakers. The 2006 census found that English, with 2,576,670 native speakers, was the most common mother tongue of Albertans, representing 79.99% of the population. The next most common mother tongues were Chinese with 97,275 native speakers (3.02%), followed by German with 84,505 native speakers (2.62%) and French with 61,225 (1.90%). Other mother tongues include: Punjabi, with 36,320 native speakers (1.13%); Tagalog, with 29,740 (0.92%); Ukrainian, with 29,455 (0.91%); Spanish, with 29,125 (0.90%); Polish, with 21,990 (0.68%); Arabic, with 20,495 (0.64%); Dutch, with 19,980 (0.62%); and Vietnamese, with 19,350 (0.60%). The most common aboriginal language is Cree 17,215 (0.53%). Other common mother tongues include Italian with 13,095 speakers (0.41%); Urdu with 11,275 (0.35%); and Korean with 10,845 (0.33%); then Hindi 8,985 (0.28%); Persian 7,700 (0.24%); Portuguese 7,205 (0.22%); and Hungarian 6,770 (0.21%). According to Statistics Canada, Alberta is home to the second-highest proportion (2%) of Francophones in western Canada (after Manitoba). Despite this, relatively few Albertans claim French as their mother tongue. Many of Alberta's French-speaking residents live in the central and northwestern regions of the province, after migration from other areas of Canada or descending from Métis. Ethnicity Alberta has considerable ethnic diversity. In line with the rest of Canada, many are descended from immigrants of Western European nations, notably England, Scotland, Ireland, Wales and France, but large numbers later came from other regions of Europe, notably Germany, Ukraine and Scandinavia."
  },
  {
   "id": "arxiv-00634",
   "text": "in this representation the larger inclination of the ridges mean lower propagation speeds and vice versa . note , that by projecting the velocities , we are able to separate the modes only in the magnetically dominated atmosphere , i.e. above the solid line in fig . [ fig : modes ] . the figure shows how the incident fast mode wave propagates to the equipartition layer and then splits into several components . the alfvn wave is produced by mode conversion above 0.2 mm ( left panel ) and propagates upwards with the ( rapid ) alfvn speed , confirmed by almost vertical inclination of the ridges . conversely , the essentially magnetic fast - mode low- wave produced in the upper atmosphere ( middle panel ) is reflected , and its velocity variations in the upper layers vanish with height . the ( acoustic ) slow - mode low- wave escapes to the upper atmosphere tunnelling over the cut - off layer due to the field inclination of . the amplitudes of the velocity variations of the alfvn wave are comparable to those of the slow wave . left panel : log of the ratio to for projected velocities and magnetic field variations , averaged over all , as a function of . black line : fast mode ( projection ) ; red line : alfvn mode ( ) ; blue line : slow mode ( ) . right panel : phase shift between the projected variations of and , as a function of for selected ."
  }
 ]
}

WORK = "/kaggle/working"
MODEL_PATH = "/kaggle/input/models/qwen-lm/qwen-3/transformers/0.6b/1"
ADAPTER_DIR = "/kaggle/input/datasets/idalextan/kg-tracer-lf-adapter"


def log(msg: str) -> None:
    print(msg, flush=True)


def check_env() -> None:
    log("=== env ===")
    import torch

    log(f"torch: {torch.__version__} cuda={torch.cuda.is_available()}")
    if torch.cuda.is_available():
        log(f"gpu: {torch.cuda.get_device_name(0)}  count={torch.cuda.device_count()}")
    for p in (MODEL_PATH, ADAPTER_DIR):
        ok = os.path.exists(p)
        log(f"{'OK ' if ok else 'MISSING'} {p}")
        if not ok:
            raise SystemExit(f"required path missing: {p}")
    cfg = os.path.join(ADAPTER_DIR, "adapter_config.json")
    if not os.path.exists(cfg):
        raise SystemExit(f"no adapter_config.json under {ADAPTER_DIR}")


def _parse_answer(raw: str) -> dict:
    raw = raw.strip()
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"no JSON object in completion: {raw[:200]!r}")
    return json.loads(raw[start : end + 1])


def install() -> None:
    """Pin the stack the v4 training kernel validated, and neutralise torchao.

    The Kaggle image pre-installs torchao 0.10.0; peft 0.18.1's
    `PeftModel.from_pretrained` hard-fails on it ("only versions above 0.16.0
    are supported") before it even reads the adapter. Uninstalling is enough —
    inference does not use torchao.
    """
    import importlib.metadata as md
    import subprocess

    log("=== install stack ===")

    def ver(pkg: str) -> str:
        try:
            return md.version(pkg)
        except md.PackageNotFoundError:
            return "MISSING"

    for p in ("torchao", "transformers", "peft"):
        log(f"pre {p}: {ver(p)}")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "uninstall", "-y", "torchao"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    subprocess.check_call(
        [
            sys.executable, "-m", "pip", "install", "--quiet",
            "transformers>=4.49.0,<5.0.0",
            "peft>=0.14.0,<=0.18.1",
        ]
    )
    for p in ("torchao", "transformers", "peft"):
        log(f"post {p}: {ver(p)}")


def infer() -> None:
    log("=== inference on 10 eval passages (max_new_tokens=8192) ===")
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH, torch_dtype=torch.bfloat16, device_map="cuda", trust_remote_code=True
    )
    model = PeftModel.from_pretrained(model, ADAPTER_DIR).merge_and_unload()
    model.eval()

    prompt = INPUTS["student_prompt"]
    rows = []
    for i, p in enumerate(INPUTS["passages"], 1):
        content = f"{prompt}\n{p['text']}"
        msgs = [{"role": "user", "content": content}]
        text = tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )
        inputs = tokenizer([text], return_tensors="pt").to("cuda")
        with torch.no_grad():
            # Greedy (do_sample=False) degenerates to repetition loops on long
            # structured output (HF docs: greedy "breaks down ... begins to
            # repeat"; Qwen3's own default is sampling temp 0.6/top_p 0.95).
            # temperature 0.7 + top_p 0.95 + repetition_penalty 1.15 follows
            # the documented ranges for structured output.
            gen = model.generate(
                **inputs, max_new_tokens=8192, do_sample=True,
                temperature=0.7, top_p=0.95, repetition_penalty=1.15,
            )
        out_ids = gen[0][inputs["input_ids"].shape[1]:]
        raw = tokenizer.decode(out_ids, skip_special_tokens=True)
        with open(os.path.join(WORK, f"raw_{p['id']}.txt"), "w", encoding="utf-8") as f:
            f.write(raw)
        try:
            parsed = _parse_answer(raw)
        except Exception as e:  # noqa: BLE001
            log(f"[{i}/10] {p['id']}: PARSE FAIL ({e}) len={len(raw)}")
            parsed = {"entities": [], "relationships": []}
        rows.append({"id": p["id"], "entities": parsed.get("entities", []),
                     "relationships": parsed.get("relationships", [])})
        log(f"[{i}/10] {p['id']}: entities={len(rows[-1]['entities'])} "
            f"rels={len(rows[-1]['relationships'])} raw_len={len(raw)}")

    pred_path = os.path.join(WORK, "predictions.jsonl")
    with open(pred_path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    log(f"wrote {pred_path} ({len(rows)} rows)")
    # CSV summary so Kaggle output listing is greppable without opening files
    with open(os.path.join(WORK, "summary.csv"), "w", encoding="utf-8") as f:
        f.write("id,entities,relationships\n")
        for r in rows:
            f.write(f"{r['id']},{len(r['entities'])},{len(r['relationships'])}\n")


def main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args(argv)
    check_env()
    install()
    infer()
    log("=== DONE ===")
    return 0


sys.exit(main())
